---
title: '<header style="text-align: center">
			<h1 style="font-weight: bold; font-size: 44px">2016 Brussels Bombings</h1>
			<h2>Air Traffic Analysis</h2>
		</header>'
author: '<div style="text-align: center">
			<span style="display: inline-block; width: 30%; margin: 0 5px">[Ramiro Balado Ordax](https://github.com/Qjammer)</span>
			<span style="display: inline-block; width: 30%; margin: 0 5px">[Alejandro Hernández Rubio](https://github.com/Shyryuu)</span>
			<span style="display: inline-block; width: 30%; margin: 0 5px">[Pol Mesalles Ripoll](https://github.com/polmes)</span>
		</div>'
# date: "DD/MM/YYYY"
output:
    rmarkdown::html_document:
        theme: cosmo
        highlight: tango
        number_sections: true
        toc: true
        toc_float: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Air Traffic

```{r, fig.align='center'}
ddr.map(data$real$routes[1:1000], autocenter = FALSE)
```

```{r, fig.align='center'}
ddr.times(data$real$flights, bru, event)
```

On the day of the event, March 22, 2016, there were a total of `r div[, .N]` diverted flights that had intended to land on Brussels Airport (EBBR).

```{r, fig.align='center'}
ddr.map(data$real$routes[id %in% div[, id]], autocenter = FALSE)
```

## TODO

- N flights vs. time with orig/dest at EBBR
- N diverted flights vs. time with dest EBBR

# Airports

The nearby airports to EBBR include:
- EBCI (Brussels South Charleroi)
- EBLF (Liège)
- EHEH (Eindhoven)
- EBAW (Antwerp)
- LFQQ (Lille)

# Airlines
